# Generated by Django 5.0.4 on 2024-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_app', '0002_alter_testmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='image_m',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
