# Generated by Django 5.0.4 on 2024-07-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_app', '0003_testmodel_image_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripdetails',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
