# Generated by Django 5.0.4 on 2024-07-11 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_app', '0004_stripdetails_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=255)),
                ('answer_option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, null=True, size=None)),
                ('corect_answer', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_mcq', models.BooleanField(default=False)),
                ('is_arabic', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ability',
            },
        ),
    ]
